#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/autocompressor/modular_autocompressor.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_autocompressor.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2025 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig
from ...modeling_rope_utils import RopeParameters
from ...utils import auto_docstring
from ...utils.type_validators import interval


@auto_docstring(checkpoint="princeton-nlp/AutoCompressor-Llama-2-7b-6k")
@strict
class AutoCompressorConfig(PreTrainedConfig):
    r"""
    Configuration class for the [AutoCompressor](https://huggingface.co/papers/2305.14788) architecture.

    AutoCompressor extends Llama with learnable summary tokens that compress long contexts into a compact
    `soft_prompt` representation for downstream generation.

    Args:
        summary_length (`int`, *optional*, defaults to 50):
            Number of summary vectors appended at the end of each segment during compression. Set to `0` to disable
            summary tokens.
        accumulate_summary (`bool`, *optional*, defaults to `True`):
            Whether to concatenate summary vectors from all previous segments into the soft prompt passed to the next
            segment.
        segment_gradient_checkpointing (`bool`, *optional*, defaults to `True`):
            Whether to apply gradient checkpointing on non-final segments during training.

    ```python
    >>> from transformers import AutoCompressorConfig, AutoCompressorForCausalLM

    >>> configuration = AutoCompressorConfig()
    >>> model = AutoCompressorForCausalLM(configuration)
    ```
    """

    model_type = "autocompressor"
    keys_to_ignore_at_inference = ["past_key_values"]
    # Default tensor parallel plan for base model `AutoCompressorModel`
    base_model_tp_plan = {
        "layers.*.self_attn.q_proj": "colwise",
        "layers.*.self_attn.k_proj": "colwise",
        "layers.*.self_attn.v_proj": "colwise",
        "layers.*.self_attn.o_proj": "rowwise_allreduce",
        "layers.*.mlp.gate_proj": "colwise",
        "layers.*.mlp.up_proj": "colwise",
        "layers.*.mlp.down_proj": "rowwise_allreduce",
    }
    base_model_sp_plan = {
        "embed_tokens": "vocab_reduce_scatter",
        "layers.*.input_layernorm": "activation",
        "layers.*.self_attn": "module_allgather_hidden_states",
        "layers.*.self_attn.q_proj": "colwise",
        "layers.*.self_attn.k_proj": "colwise",
        "layers.*.self_attn.v_proj": "colwise",
        "layers.*.self_attn.o_proj": "rowwise_reduce_scatter",
        "layers.*.post_attention_layernorm": "activation",
        "layers.*.mlp": "module_allgather",
        "layers.*.mlp.gate_proj": "colwise",
        "layers.*.mlp.up_proj": "colwise",
        "layers.*.mlp.down_proj": "rowwise_reduce_scatter",
        "norm": "activation",
    }
    base_model_pp_plan = {
        "embed_tokens": (["input_ids"], ["inputs_embeds"]),
        "layers": (["hidden_states", "attention_mask"], ["hidden_states"]),
        "norm": (["hidden_states"], ["hidden_states"]),
    }

    base_model_fsdp_plan = {
        "embed_tokens": "free_full_weight",
        "layers.*": "free_full_weight",
        "norm": "keep_full_weight",
    }

    # Llama-2-7b defaults aligned with princeton-nlp/AutoCompressor-Llama-2-7b-6k config.json
    vocab_size: int = 32000
    hidden_size: int = 4096
    intermediate_size: int = 11008
    num_hidden_layers: int = 32
    num_attention_heads: int = 32
    num_key_value_heads: int | None = 32
    hidden_act: str = "silu"
    max_position_embeddings: int = 4096
    initializer_range: float = interval(min=0.0, max=1.0)(default=0.02)
    rms_norm_eps: float = 1e-5
    use_cache: bool = True
    pad_token_id: int | None = None
    bos_token_id: int | None = 1
    eos_token_id: int | list[int] | None = 2
    pretraining_tp: int | None = 1
    tie_word_embeddings: bool = False
    rope_parameters: RopeParameters | dict | None = None
    attention_bias: bool = False
    attention_dropout: int | float | None = 0.0
    mlp_bias: bool = False
    head_dim: int | None = None

    # AutoCompressor-specific parameters from config.json
    summary_length: int = 50
    accumulate_summary: bool = True
    segment_gradient_checkpointing: bool = True

    def __post_init__(self, **kwargs):
        if self.head_dim is None:
            self.head_dim = self.hidden_size // self.num_attention_heads
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads

        super().__post_init__(**kwargs)

    def validate_architecture(self):
        """Part of `@strict`-powered validation. Validates the architecture of the config."""
        if self.hidden_size % self.num_attention_heads != 0:
            raise ValueError(
                f"The hidden size ({self.hidden_size}) is not a multiple of the number of attention "
                f"heads ({self.num_attention_heads})."
            )


__all__ = ["AutoCompressorConfig"]
