#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/autocompressor/modular_autocompressor.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_autocompressor.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2025 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from collections.abc import Callable
from dataclasses import dataclass
from typing import Optional

import torch
import torch.nn as nn
import torch.utils.checkpoint

from ...activations import ACT2FN
from ...cache_utils import Cache, DynamicCache
from ...generation import GenerationMixin
from ...integrations import use_kernel_forward_from_hub, use_kernel_func_from_hub, use_kernelized_func
from ...masking_utils import create_causal_mask
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutputWithPast, CausalLMOutputWithPast
from ...modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring, can_return_tuple
from ...utils.generic import maybe_autocast, merge_with_config_defaults
from ...utils.output_capturing import capture_outputs
from .configuration_autocompressor import AutoCompressorConfig


@dataclass
class AutoCompressorCausalLMOutputWithPast(CausalLMOutputWithPast):
    r"""
    Args:
        soft_prompt (`torch.FloatTensor` of shape `(batch_size, num_summary_tokens, hidden_size)`, *optional*):
            Compressed summary vectors produced when `output_soft_prompt=True`. Can be passed back to `forward` or
            `generate` via the `soft_prompt` argument.
    """

    soft_prompt: torch.FloatTensor | None = None


@use_kernel_forward_from_hub("RMSNorm")
class AutoCompressorRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps: float = 1e-6) -> None:
        """
        AutoCompressorRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class AutoCompressorMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=config.mlp_bias)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=config.mlp_bias)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=config.mlp_bias)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


@use_kernel_func_from_hub("rotary_pos_emb")
def apply_rotary_pos_emb(q, k, cos, sin, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        attn_weights = attn_weights + attention_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


@use_kernelized_func(apply_rotary_pos_emb)
class AutoCompressorAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: AutoCompressorConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        attention_mask: torch.Tensor | None = None,
        past_key_values: Cache | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, torch.Tensor]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_values is not None:
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx)

        attention_interface: Callable = ALL_ATTENTION_FUNCTIONS.get_interface(
            self.config._attn_implementation, eager_attention_forward
        )

        attn_output, attn_weights = attention_interface(
            self,
            query_states,
            key_states,
            value_states,
            attention_mask,
            dropout=0.0 if not self.training else self.attention_dropout,
            scaling=self.scaling,
            **kwargs,
        )

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class AutoCompressorDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: AutoCompressorConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = AutoCompressorAttention(config=config, layer_idx=layer_idx)

        self.mlp = AutoCompressorMLP(config)
        self.input_layernorm = AutoCompressorRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = AutoCompressorRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        use_cache: bool | None = False,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)
        # Self Attention
        hidden_states, _ = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            use_cache=use_cache,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states
        return hidden_states


@auto_docstring
class AutoCompressorPreTrainedModel(PreTrainedModel):
    config: AutoCompressorConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["LlamaDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn = True
    _supports_sdpa = True
    _supports_flex_attn = True

    _can_compile_fullgraph = True
    _supports_attention_backend = True
    _can_record_outputs = {
        "hidden_states": AutoCompressorDecoderLayer,
        "attentions": AutoCompressorAttention,
    }
    config_class = AutoCompressorConfig


class AutoCompressorRotaryEmbedding(nn.Module):
    inv_freq: torch.Tensor  # fix linting for `register_buffer`

    def __init__(self, config: AutoCompressorConfig, device=None):
        super().__init__()
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config

        self.rope_type = self.config.rope_parameters["rope_type"]
        rope_init_fn: Callable = self.compute_default_rope_parameters
        if self.rope_type != "default":
            rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]
        inv_freq, self.attention_scaling = rope_init_fn(self.config, device)

        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.register_buffer("original_inv_freq", inv_freq.clone(), persistent=False)

    @staticmethod
    def compute_default_rope_parameters(
        config: AutoCompressorConfig | None = None,
        device: Optional["torch.device"] = None,
        seq_len: int | None = None,
    ) -> tuple["torch.Tensor", float]:
        """
        Computes the inverse frequencies according to the original RoPE implementation
        Args:
            config ([`~transformers.PreTrainedConfig`]):
                The model configuration.
            device (`torch.device`):
                The device to use for initialization of the inverse frequencies.
            seq_len (`int`, *optional*):
                The current sequence length. Unused for this type of RoPE.
        Returns:
            Tuple of (`torch.Tensor`, `float`), containing the inverse frequencies for the RoPE embeddings and the
            post-processing scaling factor applied to the computed cos/sin (unused in this type of RoPE).
        """
        base = config.rope_parameters["rope_theta"]
        dim = getattr(config, "head_dim", None) or config.hidden_size // config.num_attention_heads

        attention_factor = 1.0  # Unused in this type of RoPE

        # Compute the inverse frequencies
        inv_freq = 1.0 / (
            base ** (torch.arange(0, dim, 2, dtype=torch.int64).to(device=device, dtype=torch.float) / dim)
        )
        return inv_freq, attention_factor

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with maybe_autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


@auto_docstring
class AutoCompressorModel(AutoCompressorPreTrainedModel):
    def __init__(self, config: AutoCompressorConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [AutoCompressorDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = AutoCompressorRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = AutoCompressorRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()

    @merge_with_config_defaults
    @capture_outputs
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        use_cache: bool | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPast:
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds: torch.Tensor = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache(config=self.config)

        if position_ids is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            position_ids = torch.arange(inputs_embeds.shape[1], device=inputs_embeds.device) + past_seen_tokens
            position_ids = position_ids.unsqueeze(0)

        causal_mask = create_causal_mask(
            config=self.config,
            inputs_embeds=inputs_embeds,
            attention_mask=attention_mask,
            past_key_values=past_key_values,
            position_ids=position_ids,
        )

        hidden_states = inputs_embeds
        position_embeddings = self.rotary_emb(hidden_states, position_ids=position_ids)

        for decoder_layer in self.layers[: self.config.num_hidden_layers]:
            hidden_states = decoder_layer(
                hidden_states,
                attention_mask=causal_mask,
                position_embeddings=position_embeddings,
                position_ids=position_ids,
                past_key_values=past_key_values,
                use_cache=use_cache,
                **kwargs,
            )

        hidden_states = self.norm(hidden_states)
        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values,
        )


@auto_docstring
class AutoCompressorForCausalLM(AutoCompressorPreTrainedModel, GenerationMixin):
    _tied_weights_keys = {"lm_head.weight": "model.embed_tokens.weight"}
    _tp_plan = {"lm_head": "colwise_allgather"}
    _sp_plan = {"lm_head": "colwise_loss_parallel"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}
    _fsdp_plan = {"lm_head": "keep_full_weight"}

    def __init__(self, config: AutoCompressorConfig):
        super().__init__(config)
        self.model = AutoCompressorModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)
        self._setup_autocompressor(config)

        # Initialize weights and apply final processing
        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | dict | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        labels: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        logits_to_keep: int | torch.Tensor = 0,
        soft_prompt: torch.FloatTensor | None = None,
        output_soft_prompt: bool | None = None,
        segment_lengths: int | list[int] | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> AutoCompressorCausalLMOutputWithPast:
        r"""
        Args:
            soft_prompt (`torch.FloatTensor` of shape `(batch_size, num_summary_tokens, hidden_size)`, *optional*):
                Pre-computed summary vectors to prepend to the current segment (e.g. from a prior compression pass).
            output_soft_prompt (`bool`, *optional*):
                Whether to return compressed summary vectors in `soft_prompt`.
            segment_lengths (`int` or `list[int]`, *optional*):
                Length(s) of segments used when compressing a long sequence without `past_key_values`. Defaults to the
                full input length when not provided.
        """
        if self.config.summary_length == 0:
            return self._forward_standard_causal_lm(
                input_ids=input_ids,
                attention_mask=attention_mask,
                position_ids=position_ids,
                past_key_values=past_key_values
                if not isinstance(past_key_values, dict)
                else past_key_values["past_key_values"],
                inputs_embeds=inputs_embeds,
                labels=labels,
                use_cache=use_cache,
                logits_to_keep=logits_to_keep,
                **kwargs,
            )

        uses_autocompressor_path = (
            output_soft_prompt
            or soft_prompt is not None
            or segment_lengths is not None
            or isinstance(past_key_values, dict)
        )
        if not uses_autocompressor_path:
            return self._forward_standard_causal_lm(
                input_ids=input_ids,
                attention_mask=attention_mask,
                position_ids=position_ids,
                past_key_values=past_key_values,
                inputs_embeds=inputs_embeds,
                labels=labels,
                use_cache=use_cache,
                logits_to_keep=logits_to_keep,
                **kwargs,
            )

        if input_ids is not None and inputs_embeds is not None:
            raise ValueError("AutoCompressor does not support both `input_ids` and `inputs_embeds` at the same time.")

        return_dict = kwargs.pop("return_dict", self.config.use_return_dict)
        use_cache = use_cache if use_cache is not None else self.config.use_cache

        past_key_values, soft_prompt, past_key_values_softprompt_length = self._unpack_past_key_values(
            past_key_values, soft_prompt
        )
        past_key_values_length = self._get_past_key_values_length(past_key_values) - past_key_values_softprompt_length

        if inputs_embeds is None:
            if input_ids is None:
                raise ValueError("You must specify either `input_ids` or `inputs_embeds`.")
            inputs_embeds = self.get_input_embeddings()(input_ids)

        batch_size = inputs_embeds.size(0)
        embed_dtype = inputs_embeds.dtype
        device = inputs_embeds.device
        summary_token_embeds = self._get_summary_token_embeds(batch_size, device, embed_dtype)

        if past_key_values is None:
            if segment_lengths is None:
                segment_lengths = inputs_embeds.size(1)
            if isinstance(segment_lengths, int):
                segment_lengths = [segment_lengths]

            if attention_mask is None:
                attention_mask = torch.ones(batch_size, inputs_embeds.size(1), dtype=torch.long, device=device)

            inputs_embeds_list = torch.split(inputs_embeds, segment_lengths, dim=1)
            attention_mask_list = torch.split(attention_mask, segment_lengths, dim=1)
            summary_token_embeds_list = (summary_token_embeds,) * (len(inputs_embeds_list) - 1) + (
                summary_token_embeds if output_soft_prompt else summary_token_embeds[:, :0],
            )
        else:
            if attention_mask is None:
                attention_mask = torch.ones(
                    batch_size, inputs_embeds.size(1) + past_key_values_length, dtype=torch.long, device=device
                )

            if (
                use_cache
                and segment_lengths is not None
                and past_key_values_length + inputs_embeds.size(1) == segment_lengths
            ):
                output_soft_prompt = True
                inputs_embeds_list = (inputs_embeds, inputs_embeds[:, :0])
                attention_mask_list = (attention_mask, attention_mask[:, :0])
                summary_token_embeds_list = (summary_token_embeds, summary_token_embeds[:, :0])
            else:
                inputs_embeds_list = (inputs_embeds,)
                attention_mask_list = (attention_mask,)
                summary_token_embeds_list = (
                    summary_token_embeds if output_soft_prompt else summary_token_embeds[:, :0],
                )

        if soft_prompt is None:
            soft_prompt = inputs_embeds[:, :0]

        last_hidden_state_list = []
        output_attentions = kwargs.get("output_attentions", False)
        output_hidden_states = kwargs.get("output_hidden_states", False)
        output_attentions_list = []
        output_hidden_states_list = []
        segment_outputs = None

        for step, segment_summary_embeds in enumerate(summary_token_embeds_list):
            is_last_step = step == len(inputs_embeds_list) - 1
            segment_gradient_checkpointing = (
                self.config.segment_gradient_checkpointing and self.training and not is_last_step
            )

            segment_outputs, segment_hidden_states, new_soft_prompt = self._forward_segment(
                soft_prompt.to(embed_dtype),
                inputs_embeds_list[step],
                segment_summary_embeds,
                attention_mask_list[step],
                past_key_values,
                use_cache,
                segment_gradient_checkpointing,
                past_key_values_softprompt_length,
                position_ids=position_ids,
                **kwargs,
            )

            last_hidden_state_list.append(segment_hidden_states)

            if self.config.accumulate_summary:
                soft_prompt = torch.cat([soft_prompt, new_soft_prompt], dim=1)
            elif new_soft_prompt.size(1) > 0:
                soft_prompt = new_soft_prompt

            if output_attentions:
                output_attentions_list.append(segment_outputs.attentions)
            if output_hidden_states:
                output_hidden_states_list.append(segment_outputs.hidden_states)

            past_key_values = None
            past_key_values_softprompt_length = 0

        past_key_values = segment_outputs.past_key_values if segment_outputs is not None else None

        last_hidden_states = torch.cat(last_hidden_state_list, dim=1)
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(last_hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        output = AutoCompressorCausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=self._wrap_past_key_values(past_key_values, soft_prompt),
            hidden_states=output_hidden_states_list if output_hidden_states and output_hidden_states_list else None,
            attentions=output_attentions_list if output_attentions and output_attentions_list else None,
            soft_prompt=soft_prompt,
        )

        if return_dict:
            return output
        return tuple(
            v
            for v in [
                output.loss,
                output.logits,
                output.past_key_values,
                output.hidden_states,
                output.attentions,
                output.soft_prompt,
            ]
            if v is not None
        )

    def _setup_autocompressor(self, config: AutoCompressorConfig) -> None:
        if config.summary_length > 0:
            embed_dim = self.get_input_embeddings().embedding_dim
            self.embed_summary = nn.Embedding(config.summary_length, embed_dim)
            eos_token_id = config.eos_token_id
            if isinstance(eos_token_id, list):
                eos_token_id = eos_token_id[0]
            self.embed_summary.weight.data.copy_(self.get_input_embeddings().weight[eos_token_id])

    def _get_past_key_values_length(self, past_key_values: Cache | None) -> int:
        if past_key_values is None:
            return 0
        return past_key_values.get_seq_length()

    def _get_summary_token_embeds(self, batch_size: int, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
        if self.config.summary_length > 0:
            summary_token_ids = torch.arange(self.config.summary_length, device=device, dtype=torch.long)
            summary_token_ids = summary_token_ids.unsqueeze(0).expand(batch_size, -1)
            return self.embed_summary(summary_token_ids).to(dtype)
        return torch.empty(batch_size, 0, self.config.hidden_size, device=device, dtype=dtype)

    def _unpack_past_key_values(
        self, past_key_values: Cache | dict | None, soft_prompt: torch.Tensor | None
    ) -> tuple[Cache | None, torch.Tensor | None, int]:
        past_key_values_softprompt_length = 0
        if isinstance(past_key_values, dict):
            soft_prompt = past_key_values.get("soft_prompt", soft_prompt)
            past_key_values = past_key_values.get("past_key_values")
            if soft_prompt is not None:
                past_key_values_softprompt_length = soft_prompt.size(1)
        return past_key_values, soft_prompt, past_key_values_softprompt_length

    def _wrap_past_key_values(
        self, past_key_values: Cache | None, soft_prompt: torch.Tensor | None
    ) -> Cache | dict | None:
        if past_key_values is None:
            return None
        return {"past_key_values": past_key_values, "soft_prompt": soft_prompt}

    def _forward_standard_causal_lm(
        self,
        input_ids: torch.LongTensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.LongTensor | None = None,
        past_key_values: Cache | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        labels: torch.LongTensor | None = None,
        use_cache: bool | None = None,
        logits_to_keep: int | torch.Tensor = 0,
        **kwargs: Unpack[TransformersKwargs],
    ) -> AutoCompressorCausalLMOutputWithPast:
        # Do not call super().forward(): modular conversion inlines Llama and breaks MRO.
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            **kwargs,
        )
        hidden_states = outputs.last_hidden_state
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])
        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)
        return AutoCompressorCausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            soft_prompt=None,
        )

    def _forward_segment(
        self,
        soft_prompt: torch.Tensor,
        segment_embeds: torch.Tensor,
        summary_token_embeds: torch.Tensor,
        segment_attention_mask: torch.Tensor,
        past_key_values: Cache | None,
        use_cache: bool | None,
        segment_gradient_checkpointing: bool,
        past_key_values_softprompt_length: int,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[CausalLMOutputWithPast, torch.Tensor, torch.Tensor]:
        batch_size = segment_embeds.size(0)
        summary_length = summary_token_embeds.size(1)

        if past_key_values_softprompt_length > 0:
            softprompt_length = 0
            segment_embeds = torch.cat([segment_embeds, summary_token_embeds], dim=1)
            device = segment_embeds.device
            attn_dtype = segment_attention_mask.dtype
            segment_attention_mask = torch.cat(
                [
                    torch.ones(batch_size, past_key_values_softprompt_length, device=device, dtype=attn_dtype),
                    segment_attention_mask,
                    torch.ones(batch_size, summary_length, device=device, dtype=attn_dtype),
                ],
                dim=1,
            )
        else:
            softprompt_length = soft_prompt.size(1)
            segment_embeds = torch.cat([soft_prompt, segment_embeds, summary_token_embeds], dim=1)
            device = segment_embeds.device
            attn_dtype = segment_attention_mask.dtype
            segment_attention_mask = torch.cat(
                [
                    torch.ones(batch_size, softprompt_length, device=device, dtype=attn_dtype),
                    segment_attention_mask,
                    torch.ones(batch_size, summary_length, device=device, dtype=attn_dtype),
                ],
                dim=1,
            )

        def decoder(
            segment_embeds,
            segment_attention_mask,
            segment_past_key_values,
            softprompt_length,
            past_key_values_softprompt_length,
            summary_length,
        ):
            forward_kwargs = dict(kwargs)
            position_ids = forward_kwargs.get("position_ids")
            if position_ids is not None and position_ids.size(1) != segment_embeds.size(1):
                # Generation passes position_ids for prompt tokens only; soft_prompt/summary extend the sequence.
                forward_kwargs.pop("position_ids", None)
            return self.model(
                inputs_embeds=segment_embeds,
                attention_mask=segment_attention_mask,
                past_key_values=segment_past_key_values,
                use_cache=use_cache,
                **forward_kwargs,
            )

        if segment_gradient_checkpointing:
            outputs = torch.utils.checkpoint.checkpoint(
                decoder,
                segment_embeds,
                segment_attention_mask,
                past_key_values,
                softprompt_length,
                past_key_values_softprompt_length,
                summary_length,
                use_reentrant=False,
            )
        else:
            outputs = decoder(
                segment_embeds,
                segment_attention_mask,
                past_key_values,
                softprompt_length,
                past_key_values_softprompt_length,
                summary_length,
            )

        total_length = outputs.last_hidden_state.size(1)
        segment_last_hidden_states = outputs.last_hidden_state[:, softprompt_length : total_length - summary_length]
        new_soft_prompt = outputs.last_hidden_state[:, total_length - summary_length :]

        return outputs, segment_last_hidden_states, new_soft_prompt

    def prepare_inputs_for_generation(
        self,
        input_ids: torch.LongTensor,
        past_key_values: Cache | dict | None = None,
        attention_mask: torch.LongTensor | None = None,
        inputs_embeds: torch.FloatTensor | None = None,
        is_first_iteration: bool | None = False,
        **kwargs,
    ):
        model_kwargs = dict(kwargs)
        if isinstance(past_key_values, dict):
            # After the first step, soft_prompt lives in the cache bundle; do not prepend it again.
            model_kwargs.pop("soft_prompt", None)
            past_key_values_for_super = past_key_values.get("past_key_values")
        else:
            past_key_values_for_super = past_key_values

        model_inputs = super().prepare_inputs_for_generation(
            input_ids,
            past_key_values=past_key_values_for_super,
            attention_mask=attention_mask,
            inputs_embeds=inputs_embeds,
            is_first_iteration=is_first_iteration,
            **model_kwargs,
        )

        if isinstance(past_key_values, dict):
            model_inputs["past_key_values"] = past_key_values

        return model_inputs


__all__ = [
    "AutoCompressorCausalLMOutputWithPast",
    "AutoCompressorPreTrainedModel",
    "AutoCompressorModel",
    "AutoCompressorForCausalLM",
]
